version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.email "satyampandya10@gmail.com"
            git config --global user.name "satyampandya"
      - run:
          name: Sync AOSP source code and build ROM
          command: |
            mkdir ~/infinity && cd ~/infinity
            curl https://storage.googleapis.com/git-repo-downloads/repo > repo
            chmod a+x repo

            # Initialize repo
            ./repo init --depth=1 --no-repo-verify --git-lfs -u https://github.com/ProjectInfinity-X/manifest -b QPR3 -g default,-mips,-darwin,-notdefault

            #sync up
            ./repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4

            # Clone trees
            git clone https://github.com/satyampandya/device_xiaomi_vince.git -b infinity-14 device/xiaomi/vince
            git clone https://github.com/satyampandya/vendor_xiaomi_vince.git -b lineage-21 vendor/xiaomi/vince
            git clone https://github.com/satyampandya/kernel_xiaomi_msm8953.git -b lineage-21 kernel/xiaomi/msm8953
            git clone https://github.com/satyampandya/device_xiaomi_msm8953-common.git -b infinity-14 device/xiaomi/msm8953-common
            git clone https://github.com/satyampandya/vendor_xiaomi_msm8953-common.git -b lineage-21 vendor/xiaomi/msm8953-common
            git clone https://github.com/satyampandya/android_hardware_xiaomi.git -b lineage-21 hardware/xiaomi
            git clone https://github.com/satyampandya/android_vendor_fingerprint_opensource_interfaces.git -b lineage-21 vendor/fingerprint/opensource/interfaces
            
            # Set up the build environment
            cd ~/infinity
            . build/envsetup.sh

            # Choose the target and build
            lunch infinix_vince-ap2a-userdebug
            mka bacon
            
      - run:
          name: Upload Build to GitHub
          command: |
            cd ~/infinity/out/target/product/vince

            # Initialize a new Git repository
            git init
            git remote add origin https://github.com/satyampandya/vince_zone.git

            # Add the files and commit
            git add .
            git commit -m "Uploading ROM build for Vince"

            # Push to GitHub using the GitHub token
            git push https://$GITHUB_TOKEN@github.com/satyampandya/vince_zone.git HEAD:master